const posts = [
  {
    id: 1,
    title: "Getting Started with Node.js",
    author: "Alice Johnson",
    content: "Node.js is a powerful JavaScript runtime built on Chrome's V8 engine. It enables server-side scripting and is widely used for building scalable network applications.",
    tags: ["nodejs", "javascript", "backend"],
    publishedAt: "2024-01-05T10:00:00Z",
    viewCount: 1420,
  },
  {
    id: 2,
    title: "A Deep Dive into React Hooks",
    author: "Bob Martinez",
    content: "React Hooks revolutionized how we write functional components. useState, useEffect, and custom hooks let you manage state and side effects without classes.",
    tags: ["react", "javascript", "frontend"],
    publishedAt: "2024-01-12T09:30:00Z",
    viewCount: 3875,
  },
  {
    id: 3,
    title: "Understanding TypeScript Generics",
    author: "Clara Nguyen",
    content: "Generics in TypeScript allow you to write reusable, type-safe code. They are one of the most powerful features of the TypeScript type system.",
    tags: ["typescript", "javascript", "backend"],
    publishedAt: "2024-01-18T14:00:00Z",
    viewCount: 2210,
  },
  {
    id: 4,
    title: "CSS Grid Layout Explained",
    author: "David Kim",
    content: "CSS Grid is a two-dimensional layout system that makes it easy to design complex web layouts. Master rows, columns, and template areas.",
    tags: ["css", "frontend", "design"],
    publishedAt: "2024-01-25T11:15:00Z",
    viewCount: 980,
  },
  {
    id: 5,
    title: "Introduction to Docker for Developers",
    author: "Alice Johnson",
    content: "Docker containers package your application and its dependencies together, ensuring consistent environments across development, staging, and production.",
    tags: ["docker", "devops", "backend"],
    publishedAt: "2024-02-03T08:45:00Z",
    viewCount: 4200,
  },
  {
    id: 6,
    title: "Building REST APIs with Express",
    author: "Elena Russo",
    content: "Express.js is the de-facto framework for building REST APIs in Node.js. Learn routing, middleware, error handling, and best practices.",
    tags: ["nodejs", "express", "backend", "api"],
    publishedAt: "2024-02-10T13:00:00Z",
    viewCount: 5510,
  },
  {
    id: 7,
    title: "PostgreSQL Performance Tuning Tips",
    author: "Frank Chen",
    content: "Slow queries can cripple your application. Discover indexing strategies, EXPLAIN ANALYZE, and query optimization techniques for PostgreSQL.",
    tags: ["postgresql", "database", "backend", "performance"],
    publishedAt: "2024-02-17T10:30:00Z",
    viewCount: 1750,
  },
  {
    id: 8,
    title: "State Management with Redux Toolkit",
    author: "Bob Martinez",
    content: "Redux Toolkit simplifies Redux development with createSlice, createAsyncThunk, and the RTK Query data-fetching utility.",
    tags: ["react", "redux", "javascript", "frontend"],
    publishedAt: "2024-02-24T09:00:00Z",
    viewCount: 2630,
  },
  {
    id: 9,
    title: "Mastering Git Branching Strategies",
    author: "Clara Nguyen",
    content: "Git Flow, trunk-based development, and GitHub Flow each have trade-offs. This guide helps you choose the right strategy for your team.",
    tags: ["git", "devops", "workflow"],
    publishedAt: "2024-03-02T15:00:00Z",
    viewCount: 3100,
  },
  {
    id: 10,
    title: "An Introduction to GraphQL",
    author: "David Kim",
    content: "GraphQL is a query language for your API. It gives clients the power to ask for exactly what they need and nothing more.",
    tags: ["graphql", "api", "backend"],
    publishedAt: "2024-03-09T11:00:00Z",
    viewCount: 4450,
  },
  {
    id: 11,
    title: "Securing Node.js Applications",
    author: "Elena Russo",
    content: "Security is not an afterthought. Learn how to protect your Node.js apps against SQL injection, XSS, CSRF, and common OWASP vulnerabilities.",
    tags: ["nodejs", "security", "backend"],
    publishedAt: "2024-03-16T08:00:00Z",
    viewCount: 6780,
  },
  {
    id: 12,
    title: "Building Accessible Web Applications",
    author: "Grace Park",
    content: "Web accessibility ensures everyone can use your application. Learn ARIA roles, semantic HTML, keyboard navigation, and color contrast best practices.",
    tags: ["accessibility", "frontend", "html", "design"],
    publishedAt: "2024-03-23T12:00:00Z",
    viewCount: 870,
  },
  {
    id: 13,
    title: "Kubernetes for Beginners",
    author: "Frank Chen",
    content: "Kubernetes orchestrates your containerized workloads across a cluster of machines. Understand pods, services, deployments, and ingress controllers.",
    tags: ["kubernetes", "devops", "docker"],
    publishedAt: "2024-03-30T10:00:00Z",
    viewCount: 5230,
  },
  {
    id: 14,
    title: "Functional Programming Patterns in JavaScript",
    author: "Alice Johnson",
    content: "Immutability, pure functions, higher-order functions, and function composition lead to code that is easier to reason about and test.",
    tags: ["javascript", "functional", "frontend", "backend"],
    publishedAt: "2024-04-06T14:30:00Z",
    viewCount: 2980,
  },
  {
    id: 15,
    title: "Testing React Components with Testing Library",
    author: "Bob Martinez",
    content: "React Testing Library encourages you to test your components the way users interact with them — through the DOM, not implementation details.",
    tags: ["react", "testing", "frontend", "javascript"],
    publishedAt: "2024-04-13T09:45:00Z",
    viewCount: 3340,
  },
  {
    id: 16,
    title: "Event-Driven Architecture with Kafka",
    author: "Grace Park",
    content: "Apache Kafka enables high-throughput, fault-tolerant event streaming. Learn producers, consumers, topics, partitions, and consumer groups.",
    tags: ["kafka", "backend", "architecture", "devops"],
    publishedAt: "2024-04-20T11:30:00Z",
    viewCount: 1920,
  },
  {
    id: 17,
    title: "Writing Clean Code: Principles and Practices",
    author: "Clara Nguyen",
    content: "Clean code is code that is easy to read, maintain, and extend. Apply SOLID principles, meaningful naming, and small focused functions.",
    tags: ["clean-code", "best-practices", "backend", "frontend"],
    publishedAt: "2024-04-27T13:00:00Z",
    viewCount: 4670,
  },
  {
    id: 18,
    title: "MongoDB Aggregation Pipeline",
    author: "David Kim",
    content: "MongoDB's aggregation pipeline lets you transform and analyze documents in powerful ways using $match, $group, $project, $lookup, and more.",
    tags: ["mongodb", "database", "backend"],
    publishedAt: "2024-05-04T10:00:00Z",
    viewCount: 2100,
  },
  {
    id: 19,
    title: "CI/CD Pipelines with GitHub Actions",
    author: "Elena Russo",
    content: "Automate your build, test, and deployment workflows directly in your GitHub repository using YAML-defined Actions workflows.",
    tags: ["github-actions", "devops", "ci-cd"],
    publishedAt: "2024-05-11T08:30:00Z",
    viewCount: 3890,
  },
  {
    id: 20,
    title: "WebSockets and Real-Time Applications",
    author: "Grace Park",
    content: "WebSockets provide a persistent, bidirectional communication channel between client and server — essential for chat apps, live dashboards, and collaborative tools.",
    tags: ["websockets", "nodejs", "backend", "real-time"],
    publishedAt: "2024-05-18T15:00:00Z",
    viewCount: 2755,
  },
];

module.exports = posts;
